// react-track-render/vite-project/src/App.tsx
import React, { useState, useEffect } from 'react'
import logo from './logo.svg'
import './App.css'
import Hello from './Hello'

function App() {
  const [count, setCount] = useState(0)
  const [list, setList] = useState([])
  useEffect(() => {
    setTimeout(() => {
      setCount('changed')
    }, 5000);
  }, [])
  return (
    <div className="App">

      <Hello text={count}/>
    </div>
  )
}

export default App

// solidjs-my-app/src/App.tsx
import { Component,createSignal } from 'solid-js';

import logo from './logo.svg';
import styles from './App.module.css';

const App: Component = (pops) => {
  const [count,setCount] = createSignal(1);
  const handleClk = ()=> setCount(count()+1)
  // createSignal
  return (
    <div class={styles.App}>
      <header class={styles.header}>
        <img src={logo} class={styles.logo} alt="logo" />
        
        <button onClick={handleClk}>

        {count()}
        </button>
      </header>
    </div>
  );
};

export default App;
